#!/usr/bin/env npx tsx
/**
 * Generates an Apex anonymous script that evaluates formulas using FormulaEval API.
 *
 * Usage: npx tsx scripts/formula-verify/generate-apex.ts > scripts/formula-verify/verify.apex
 */

import { readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const formulas = JSON.parse(readFileSync(resolve(__dirname, 'formulas.json'), 'utf-8'));

// Map our return types to FormulaEval.FormulaReturnType
const typeMap: Record<string, string> = {
  STRING: 'FormulaEval.FormulaReturnType.STRING',
  DECIMAL: 'FormulaEval.FormulaReturnType.DECIMAL',
  BOOLEAN: 'FormulaEval.FormulaReturnType.BOOLEAN',
  DATE: 'FormulaEval.FormulaReturnType.DATE_', // note: DATE_ not DATE in some orgs
  DATETIME: 'FormulaEval.FormulaReturnType.DATETIME',
};

let apex = `// Auto-generated by generate-apex.ts — do not edit manually
// Evaluates formula expressions using FormulaEval API and outputs results

Account testRec = new Account(Name='TestAccount', AnnualRevenue=50000);
List<String> results = new List<String>();

`;

for (const test of formulas.tests) {
  if (test.skip) continue;
  const escapedFormula = test.formula.replace(/'/g, "\\'");
  const returnType = typeMap[test.returnType] ?? 'FormulaEval.FormulaReturnType.STRING';
  const varName = `f_${test.id.replace(/[^a-zA-Z0-9]/g, '_')}`;

  apex += `// ${test.id}: ${test.description}\n`;
  apex += `try {\n`;
  apex += `  FormulaEval.FormulaInstance ${varName} = Formula.builder()\n`;
  apex += `    .withType(Account.class)\n`;
  apex += `    .withReturnType(${returnType})\n`;
  apex += `    .withFormula('${escapedFormula}')\n`;
  apex += `    .build();\n`;
  apex += `  Object result = ${varName}.evaluate(testRec);\n`;
  apex += `  results.add('${test.id}=' + String.valueOf(result));\n`;
  apex += `} catch (Exception e) {\n`;
  apex += `  results.add('${test.id}=ERROR:' + e.getMessage());\n`;
  apex += `}\n\n`;
}

apex += `for (String r : results) {\n`;
apex += `  System.debug(LoggingLevel.ERROR, '###FORMULA_RESULT### ' + r);\n`;
apex += `}\n`;

console.log(apex);
